name: without secrets pipeline
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: artifacts
        run: actions/checkout@v4
      - name: Docker build
        run: docker build -t bhaskar0516/nginx2:latest .

      - name: Docker credentails
        run: docker login --username=bhaskar0516 --password=Docker$16

      - name: Docker push
        run: docker push bhaskar0516/nginx2:latest